// GENERATED by build.js from @ai4a11y/toolkit (ES module source). Do not edit by hand.
(() => {
  // node_modules/@ai4a11y/toolkit/core/units.js
  var UNIT = Object.freeze({
    percent: "percent",
    // 100 = no change (fontScale)
    ratio: "ratio",
    // a unitless multiple (lineHeight, speechRate)
    em: "em",
    // typographic em (letterSpacing)
    boolean: "boolean",
    enum: "enum"
  });
  var SETTING_UNITS = Object.freeze({
    fontScale: UNIT.percent,
    lineHeight: UNIT.ratio,
    letterSpacing: UNIT.em,
    speechRate: UNIT.ratio
  });
  function coerceSetting(key, value, meta) {
    const m = meta && meta[key];
    if (!(m && m.type === "number" && Array.isArray(m.range) && typeof value === "number")) {
      return value;
    }
    const [min, max] = m.range;
    let val = value;
    if (val < min && val * 100 >= min && val * 100 <= max) val = val * 100;
    return Math.min(max, Math.max(min, val));
  }
  function coerceSettings(settings, meta) {
    if (!settings || typeof settings !== "object") return settings;
    const out = {};
    for (const [k, v] of Object.entries(settings)) out[k] = coerceSetting(k, v, meta);
    return out;
  }

  // node_modules/@ai4a11y/toolkit/core/datastore.js
  function createDatastore({ kv, clock, taxonomy, toolsRegistry = null, builtinSkills = [] }) {
    if (!kv) throw new Error("createDatastore: kv port is required");
    if (!clock) throw new Error("createDatastore: clock port is required");
    const CATALOG = {
      // -- existing stores (legacy physical keys) --
      "mine.skills": { area: "local", key: "customSkills", version: 1, def: [] },
      "mine.profiles": { area: "local", key: "customProfiles", version: 1, def: [] },
      "mine.onboardingProfile": { area: "local", key: "userProfile", version: 1, def: null },
      "mine.harnessSkills": { area: "local", key: "bhSkills", version: 1, def: {} },
      // -- reserved for the Librarian --
      // Ability profile: semi-structured, schema-versioned, SMALL — lives in
      // sync so it roams across the user's devices (Lakshmi case). Includes
      // the metaPreferences block (consent boundary, interaction style).
      "mine.profile": { area: "sync", key: "aa.mine.profile", version: 1, def: null, reserved: true },
      // Suppressions roam too: "don't suggest font changes" must hold on
      // every device.
      "mine.suppressions": { area: "sync", key: "aa.mine.suppressions", version: 1, def: [], reserved: true },
      // Append-only observation log + extraction cursor (the WAL of the
      // memory pipeline). The no-memory-zone check happens BEFORE writes
      // land here — see taxonomy.noMemoryCategories().
      "mine.episodicLog": { area: "local", key: "aa.mine.episodicLog", version: 1, def: { cursor: 0, entries: [] }, reserved: true },
      "mine.proposals": { area: "local", key: "aa.mine.proposals", version: 1, def: [], reserved: true },
      // origin → {category, source: 'hostmap'|'llm'|'user', classifiedAt,
      // taxonomyVersion}. Classify once, cache; user overrides are sticky.
      "mine.siteIndex": { area: "local", key: "aa.mine.siteIndex", version: 1, def: {}, reserved: true },
      // Materialized presentation views (core memory block, review-page
      // groups, category playbooks) rendered by the reflection job.
      "mine.views": { area: "local", key: "aa.mine.views", version: 1, def: {}, reserved: true },
      // Cross-app read grants (Phase 3): per-app, user-approved, scoped read
      // access to the AbilityModel. Sync so an approved grant roams across the
      // user's devices like the profile/suppressions. Revoke = local delete (no
      // tombstone). No migration needed — `def: []` reads as empty lazily and
      // `storeVersions` auto-picks-up the new entry, exactly like every other
      // reserved store.
      "mine.grants": { area: "sync", key: "aa.mine.grants", version: 1, def: [], reserved: true },
      // Share-audit log for cross-app sharing (Phase 3): a local, append-only
      // record of what was actually shared with which app and when. Declared
      // here so the catalog/version machinery covers it from day one; written
      // by ../sync/grants.js#recordShareAudit, called from core/librarian.js
      // (requestGrant's accept path, revokeGrant, exportAbilityModel, the
      // cross-app-insight accept path).
      "mine.shareAudit": { area: "local", key: "aa.mine.shareAudit", version: 1, def: [], reserved: true },
      // The user's own skills — SKILL.md playbooks the Engineer built and the
      // person validated (parsed Skill objects; see ../core/skill.js). Distinct
      // from `mine.skills` above (legacy customSkills = user-built adapter
      // *code*). Local, not sync: unlike the small profile/suppressions
      // records, saved skills can carry an arbitrary-length body and are not
      // performance-sensitive to roam eagerly.
      "mine.skillDocs": { area: "local", key: "aa.mine.skillDocs", version: 1, def: [] }
    };
    const MEMORY_SHARD_PREFIX = "aa.mine.memory.";
    const MEMORY_VERSION = 1;
    const META_KEY = "aa.meta";
    const ACTING_USER_KEY = "aa.actingUser";
    const VALID_ACTING_ID = /^[A-Za-z0-9_-]{1,32}$/;
    const PARTITION_SCHEME = 1;
    let _actingUserId = null;
    let _helperMode = false;
    async function rawGet(area, key, def) {
      const v = await kv.get(area, key);
      return v === void 0 ? def : v;
    }
    async function rawSet(area, key, value) {
      await kv.set(area, key, value);
    }
    function partitionKey(physKey, pid = _actingUserId) {
      return pid ? `aa.u.${pid}::${physKey}` : physKey;
    }
    function partitionView(pid) {
      const shardKey = (scope) => Datastore.memoryShardKey(scope);
      const view = {
        global: Datastore.global,
        memoryShardKey: shardKey,
        async get(name) {
          const d = CATALOG[name];
          if (!d) throw new Error(`Datastore: unknown store "${name}"`);
          return await rawGet(d.area, partitionKey(d.key, pid), structuredClone(d.def));
        },
        async set(name, value) {
          const d = CATALOG[name];
          if (!d) throw new Error(`Datastore: unknown store "${name}"`);
          await rawSet(d.area, partitionKey(d.key, pid), value);
        },
        async patch(name, fn) {
          const cur = await view.get(name);
          const next = await fn(cur);
          await view.set(name, next === void 0 ? cur : next);
          return next === void 0 ? cur : next;
        },
        async getMemoryShard(scope) {
          return await rawGet("local", partitionKey(shardKey(scope), pid), []);
        },
        async setMemoryShard(scope, records) {
          await rawSet("local", partitionKey(shardKey(scope), pid), records);
        },
        async allMemoryShards() {
          const all = await kv.getAll("local");
          const prefix = partitionKey(MEMORY_SHARD_PREFIX, pid);
          const out = {};
          for (const [key, recs] of Object.entries(all || {})) {
            if (key.startsWith(prefix)) out[key.slice(prefix.length)] = recs || [];
          }
          return out;
        }
      };
      return view;
    }
    async function loadActingUser() {
      const rec = await rawGet("local", ACTING_USER_KEY, null);
      _actingUserId = rec && typeof rec.id === "string" && VALID_ACTING_ID.test(rec.id) ? rec.id : null;
      _helperMode = !!(rec && rec.helperMode);
    }
    const MIGRATIONS = [
      {
        id: 1,
        // Baseline: stamp meta so future migrations know where they started.
        run: async () => {
        }
      },
      {
        id: 2,
        // Normalize legacy memory-record settings to canonical units. The read
        // path is now clamp-only (the `>10` %-vs-multiplier heuristic was deleted
        // from reads), so any value an old un-coerced writer stored as a
        // multiplier (e.g. fontScale:1.5) is normalized once here (→ 150) instead
        // of being second-guessed on every read. Idempotent: canonical values are
        // unchanged by coercion.
        run: async (ds) => {
          const meta = ds.global.tools() && ds.global.tools().settingsMeta || {};
          if (!Object.keys(meta).length) return;
          const shards = await ds.allMemoryShards();
          for (const [scope, recs] of Object.entries(shards)) {
            let dirty = false;
            for (const r of recs || []) {
              if (r && r.settings && typeof r.settings === "object") {
                const norm = coerceSettings(r.settings, meta);
                if (JSON.stringify(norm) !== JSON.stringify(r.settings)) {
                  r.settings = norm;
                  dirty = true;
                }
              }
            }
            if (dirty) await ds.setMemoryShard(scope, recs);
          }
        }
      },
      {
        id: 3,
        // Backfill lastConfirmedAt (Phase 2: decay now measures last CONFIRMATION,
        // not last surfacing). Idempotent: only stamps records missing the field;
        // seeds it from updatedAt/createdAt so existing records keep their age.
        run: async (ds) => {
          const shards = await ds.allMemoryShards();
          for (const [scope, recs] of Object.entries(shards)) {
            let dirty = false;
            for (const r of recs || []) {
              if (r && r.lastConfirmedAt == null) {
                r.lastConfirmedAt = r.updatedAt || r.createdAt || null;
                dirty = true;
              }
            }
            if (dirty) await ds.setMemoryShard(scope, recs);
          }
        }
      }
    ];
    const PARTITION_META_KEY = "aa.partitionMeta";
    let _migrateChain = Promise.resolve();
    async function migrateActivePartition(pid = _actingUserId) {
      if (!pid) return;
      const run = _migrateChain.then(async () => {
        const key = partitionKey(PARTITION_META_KEY, pid);
        const pm = await rawGet("local", key, null) || { lastMigration: 0 };
        const maxId = MIGRATIONS[MIGRATIONS.length - 1].id;
        if ((pm.lastMigration || 0) >= maxId) return;
        const view = partitionView(pid);
        for (const m of MIGRATIONS) {
          if (m.id <= (pm.lastMigration || 0)) continue;
          await m.run(view);
          pm.lastMigration = m.id;
        }
        pm.migratedAt = clock.now();
        await rawSet("local", key, pm);
      });
      _migrateChain = run.catch(() => {
      });
      return run;
    }
    async function runMigrations() {
      await loadActingUser();
      const activePid = _actingUserId;
      const nullView = partitionView(null);
      let meta = await rawGet("local", META_KEY, null) || { lastMigration: 0 };
      let applied = false;
      for (const m of MIGRATIONS) {
        if (m.id <= (meta.lastMigration || 0)) continue;
        await m.run(nullView);
        meta.lastMigration = m.id;
        applied = true;
      }
      meta.storeVersions = Object.fromEntries(
        Object.entries(CATALOG).map(([n, d]) => [n, d.version])
      );
      meta.memoryVersion = MEMORY_VERSION;
      meta.partitionScheme = PARTITION_SCHEME;
      meta.taxonomyVersion = taxonomy ? taxonomy.version : null;
      if (applied || !meta.lastMigratedAt) meta.lastMigratedAt = clock.now();
      await rawSet("local", META_KEY, meta);
      await migrateActivePartition(activePid);
      return meta;
    }
    const Datastore = {
      catalog() {
        return JSON.parse(JSON.stringify(CATALOG));
      },
      async get(name) {
        const d = CATALOG[name];
        if (!d) throw new Error(`Datastore: unknown store "${name}"`);
        return await rawGet(d.area, partitionKey(d.key), structuredClone(d.def));
      },
      async set(name, value) {
        const d = CATALOG[name];
        if (!d) throw new Error(`Datastore: unknown store "${name}"`);
        await rawSet(d.area, partitionKey(d.key), value);
      },
      // Read-modify-write. fn receives the current value and returns the new
      // one (or mutates and returns the same reference). KVStore writes are
      // atomic per key; this does NOT guard against concurrent patchers —
      // single-writer discipline (host background only) is what makes it safe.
      async patch(name, fn) {
        const cur = await this.get(name);
        const next = await fn(cur);
        await this.set(name, next === void 0 ? cur : next);
        return next === void 0 ? cur : next;
      },
      // Memory fact shards. One KVStore 'local' key per scope so recall reads
      // only the shards the current page needs.
      memoryShardKey(scope) {
        if (!/^(general|category:[a-z-]+|context:[a-z-]+|origin:[a-z0-9.-]+|tool:[a-zA-Z0-9_-]+)$/.test(scope)) {
          throw new Error(`Datastore: invalid memory scope "${scope}"`);
        }
        return MEMORY_SHARD_PREFIX + scope;
      },
      async getMemoryShard(scope) {
        return await rawGet("local", partitionKey(this.memoryShardKey(scope)), []);
      },
      async setMemoryShard(scope, records) {
        await rawSet("local", partitionKey(this.memoryShardKey(scope)), records);
      },
      // Every memory shard of the ACTIVE partition, as { scope: records }.
      // Replaces the Librarian's former direct `chrome.storage.local.get(null)`
      // scans, keeping the facade the single place that knows the shard prefix.
      // The partitioned prefix isolates partitions: the null partition's prefix
      // (`aa.mine.memory.`) never matches a named partition's `aa.u.<id>::…` key,
      // and a named partition's prefix matches only its own.
      async allMemoryShards() {
        const all = await kv.getAll("local");
        const prefix = partitionKey(MEMORY_SHARD_PREFIX);
        const out = {};
        for (const [key, recs] of Object.entries(all || {})) {
          if (key.startsWith(prefix)) {
            out[key.slice(prefix.length)] = recs || [];
          }
        }
        return out;
      },
      // ---- acting-user partition (Phase 3) ----
      // Switch the active partition. `id=null` restores the default single-user
      // data (today's keys, unchanged). A named id (`[A-Za-z0-9_-]{1,32}`) gives
      // a disjoint, lazily-created partition. Persists the pointer (local,
      // non-partitioned) so it survives a service-worker restart. Returns
      // {ok, id, helperMode} or {ok:false, reason:'bad-id'}.
      async setActingUser(id, opts = {}) {
        if (id != null && !(typeof id === "string" && VALID_ACTING_ID.test(id))) {
          return { ok: false, reason: "bad-id" };
        }
        _actingUserId = id == null ? null : id;
        if (opts.helperMode != null) _helperMode = !!opts.helperMode;
        await rawSet("local", ACTING_USER_KEY, { id: _actingUserId, helperMode: _helperMode });
        await migrateActivePartition();
        return { ok: true, id: _actingUserId, helperMode: _helperMode };
      },
      // The active partition + helper-mode flag. In-memory: only correct AFTER
      // loadActingUser() has run (top of runMigrations) — a caller before startup
      // completes sees the default-null partition, which is the safe default.
      getActingUser() {
        return { id: _actingUserId, helperMode: _helperMode };
      },
      // Global tier — read-only, supplied by the host at construction.
      global: {
        tools() {
          return toolsRegistry || null;
        },
        taxonomy() {
          return taxonomy || null;
        },
        // Built-in skills (SKILL.md playbooks) shipped with the host. Returns
        // an array of parsed Skill objects, or [] if the host ships none.
        skills() {
          return builtinSkills || [];
        }
      },
      runMigrations
    };
    return Datastore;
  }

  // node_modules/@ai4a11y/toolkit/platforms/chrome/ports.js
  function chromeKV() {
    const area = (name) => chrome.storage[name];
    return {
      get(areaName, key) {
        return new Promise((resolve) => {
          area(areaName).get(key, (data) => resolve(data ? data[key] : void 0));
        });
      },
      set(areaName, key, value) {
        return new Promise((resolve, reject) => {
          area(areaName).set({ [key]: value }, () => {
            if (chrome.runtime.lastError) reject(new Error(chrome.runtime.lastError.message));
            else resolve();
          });
        });
      },
      getAll(areaName) {
        return new Promise((resolve) => {
          area(areaName).get(null, (data) => resolve(data || {}));
        });
      }
    };
  }
  function chromeClock() {
    return { now: () => Date.now() };
  }

  // node_modules/@ai4a11y/toolkit/platforms/chrome/datastore.entry.js
  globalThis.Datastore = createDatastore({
    kv: chromeKV(),
    clock: chromeClock(),
    taxonomy: globalThis.AA_TAXONOMY,
    toolsRegistry: globalThis.AA_TOOLS || null,
    builtinSkills: globalThis.AA_SKILLS || []
  });
})();
