// GENERATED by build.js from @ai4a11y/toolkit (ES module source). Do not edit by hand.
(() => {
  // node_modules/@ai4a11y/toolkit/core/surface.js
  function createSurfaceAdapter(spec) {
    const id = spec.id;
    const supports = spec.supports || {};
    return {
      id,
      /** Keys this surface can render at all. */
      supportedKeys() {
        return Object.keys(supports);
      },
      /**
       * @param {Record<string, any>} settings  merged settings (canonical units).
       * @returns {{applied:Object, unmet:Array, degradedTo:Object, satisfied:boolean}}
       *   - applied: what this surface will actually render.
       *   - unmet:   [{key, value, reason: 'unsupported' | 'not-representable'}].
       *   - degradedTo: keys whose value was lowered to a representable fallback.
       *   - satisfied: true iff nothing was unmet (degraded still counts as met).
       */
      apply(settings) {
        const applied = {};
        const unmet = [];
        const degradedTo = {};
        for (const [key, value] of Object.entries(settings || {})) {
          const s = supports[key];
          if (!s) {
            unmet.push({ key, value, reason: "unsupported" });
            continue;
          }
          if (s.representable && !s.representable(value)) {
            if (s.degrade) {
              const d = s.degrade(value);
              if (d === void 0 || d === null) {
                unmet.push({ key, value, reason: "not-representable" });
                continue;
              }
              applied[key] = d;
              degradedTo[key] = d;
              continue;
            }
            unmet.push({ key, value, reason: "not-representable" });
            continue;
          }
          applied[key] = value;
        }
        return { applied, unmet, degradedTo, satisfied: unmet.length === 0 };
      }
    };
  }

  // node_modules/@ai4a11y/toolkit/core/strength.js
  var STRENGTH_RANK = Object.freeze({ hint: 0, preference: 1, floor: 2 });
  function rankOf(strength) {
    const r = STRENGTH_RANK[strength];
    return r === void 0 ? STRENGTH_RANK.preference : r;
  }

  // node_modules/@ai4a11y/toolkit/core/units.js
  var UNIT = Object.freeze({
    percent: "percent",
    // 100 = no change (fontScale)
    ratio: "ratio",
    // a unitless multiple (lineHeight, speechRate)
    em: "em",
    // typographic em (letterSpacing)
    boolean: "boolean",
    enum: "enum"
  });
  var SETTING_UNITS = Object.freeze({
    fontScale: UNIT.percent,
    lineHeight: UNIT.ratio,
    letterSpacing: UNIT.em,
    speechRate: UNIT.ratio
  });
  function coerceSetting(key, value, meta) {
    const m = meta && meta[key];
    if (!(m && m.type === "number" && Array.isArray(m.range) && typeof value === "number")) {
      return value;
    }
    const [min, max] = m.range;
    let val = value;
    if (val < min && val * 100 >= min && val * 100 <= max) val = val * 100;
    return Math.min(max, Math.max(min, val));
  }

  // node_modules/@ai4a11y/toolkit/platforms/chrome/web-surface.js
  function createWebSurface(settingsMeta = {}) {
    const supports = {};
    for (const [key, meta] of Object.entries(settingsMeta)) {
      if (meta.type === "number" && Array.isArray(meta.range)) {
        const [min, max] = meta.range;
        supports[key] = {
          unit: meta.type,
          representable: (v) => typeof v === "number" && v >= min && v <= max,
          // Out-of-range numbers degrade to the nearest bound rather than failing.
          degrade: (v) => typeof v === "number" ? Math.min(max, Math.max(min, v)) : void 0
        };
      } else {
        supports[key] = { unit: meta.type };
      }
    }
    return createSurfaceAdapter({ id: "web", supports });
  }
  var WEB_DERIVATION = {
    textSize: (v) => ({ fontScale: Math.round(Number(v) * 100) }),
    // multiplier → %
    lineSpacing: (v) => ({ lineHeight: Number(v) }),
    letterSpacing: (v) => ({ letterSpacing: Number(v) }),
    reduceMotion: (v) => ({ motionReducer: !!v }),
    darkTheme: (v) => ({ darkMode: !!v }),
    // A hearing profile gets all three tiers, cheapest-first: showCaptions turns
    // on captions the media already has (no AI); liveCaptions is the browser's own
    // on-device captioning for audio with no track at all; autoCaptions is the AI
    // enhancement that activates only when a model is wired. Naming liveCaptions
    // here matters — a receiver that INFERS it from the caption keys owns state
    // the profile never expressed, so an explicit "off" can't be recorded against
    // it and a reset can't restore it.
    captions: (v) => ({ showCaptions: !!v, liveCaptions: !!v, autoCaptions: !!v }),
    simplify: (v) => ({ autoSimplify: !!v }),
    contrast: (v) => ({ contrastMode: v === true ? "light" : v }),
    dyslexiaFont: (v) => ({ dyslexiaFont: !!v }),
    readAloudRate: (v) => ({ speechRate: Number(v) }),
    readAloud: (v) => ({ readAloud: !!v }),
    // Screen-reader (non-visual) dimensions — how a page is STRUCTURED and
    // announced, not how it looks. These are what a blind user's profile needs;
    // each maps to an already-wired catalog adapter (see tools/profiles/
    // settings.js getEnabledAdapters).
    describeImages: (v) => ({ autoDescribe: !!v }),
    labelControls: (v) => ({ autoFixLabels: !!v }),
    repairLandmarks: (v) => ({ fixLandmarks: !!v }),
    announceUpdates: (v) => ({ announceUpdates: !!v }),
    spaAnnounce: (v) => ({ spaFocus: !!v }),
    skipLinks: (v) => ({ skipLinks: !!v }),
    pageStructure: (v) => ({ pageOutline: !!v }),
    keyboardAccess: (v) => ({ keyboardNav: !!v })
  };
  function deriveWebSettings(abilityModel) {
    const settings = {};
    const strengthByKey = {};
    const unmet = [];
    const needs = abilityModel && abilityModel.needs || [];
    if (!needs.length) return { settings, strengthByKey, unmet };
    for (const need of needs) {
      const fn = WEB_DERIVATION[need.dimension];
      if (!fn) {
        unmet.push({ key: need.dimension, value: need.value, reason: "unsupported" });
        continue;
      }
      const out = fn(need.value);
      const s = need.strength || "preference";
      for (const [k, v] of Object.entries(out)) {
        if (k in settings && rankOf(s) < rankOf(strengthByKey[k])) continue;
        settings[k] = v;
        strengthByKey[k] = s;
      }
    }
    return { settings, strengthByKey, unmet };
  }
  async function resolveWebPreferences({ librarian, settingsMeta, url, contexts = [] }) {
    const prefs = await librarian.getEffectivePreferences(url, contexts);
    const model = await librarian.getAbilityModel();
    const { settings: derived, unmet } = deriveWebSettings(model);
    const settings = { ...prefs.settings };
    const provenance = { ...prefs.provenance || {} };
    for (const [k, v] of Object.entries(derived)) {
      if (!(k in settings)) {
        settings[k] = coerceSetting(k, v, settingsMeta);
        provenance[k] = "derived:ability";
      }
    }
    return {
      ...prefs,
      settings,
      provenance,
      surface: { unmet, satisfied: unmet.length === 0 }
    };
  }

  // node_modules/@ai4a11y/toolkit/platforms/chrome/web-surface.entry.js
  globalThis.WebSurface = { createWebSurface, deriveWebSettings, resolveWebPreferences };
})();
